### ISSUE TITLE
Why doesn't the running of the development server result in a development environment?

### ISSUE THREAD

**Issue by rsyring** [level12/keg-app-cookiecutter#101]
```
$ miller develop run
 * Environment: production
...
```

Seems like we could make a better default.

I ended up needing to do: `FLASK_ENV=development miller develop run`

IMO, it would be better if:

* install python-dotenv in development reqs file
* configure Keg/Flask so that they use them
* adjust the template to include a .env file that is gitignored and contains "FLASK_ENV=development".  Make a note in the readme that this is required, probably in the same area where we discuss copying the example config file.

**Comment by rsyring** [comment]
Turns out this is pretty easy to support: https://github.com/level12/miller-poultry/commit/5df3e8681142ac7a3c0ac8c3172ac0656bf4e577

I did this in the top-level module, instead of in config files, due to the need to have that environment variable set [before the Flask app is initialized](https://flask.palletsprojects.com/en/1.1.x/config/#environment-and-debug-features).

**Comment by bchopson** [comment]
This is one of the things I use https://direnv.net/ for.

**Comment by bchopson** [comment]
Looks like flask supports a `.flaskenv` file when `python-dotenv` is installed: https://flask.palletsprojects.com/en/1.1.x/cli/#environment-variables-from-dotenv
