### ISSUE TITLE
Default nav needs login link

### ISSUE THREAD

**Issue by rsyring** [level12/keg-app-cookiecutter#136]
And also should be smarter about when login/logout shows based on authentication status of user.  See: https://github.com/level12/keg-auth/issues/125

**Comment by guruofgentoo** [comment]
This should do the trick with keg-auth 0.4.0:
```
NavItem('Logout', NavURL('auth.logout')),
NavItem('Login', NavURL('auth.login', requires_anonymous=True)),
```
