### ISSUE TITLE
demo objects or no demo objects

### ISSUE THREAD

**Issue by guruofgentoo** [level12/keg-app-cookiecutter#139]
We had a demo setup in the cookiecutter, then decided it was a lot of effort to remove it from new apps. I.e. hard to tell what belonged to the set of demo objects, and what absolutely had to stay.

Recently, it appears we have demo objects again. We should probably discuss the intent of these given prior removal. They need to be removed right away from any new project, so they don't really serve as a "template" in the target app.

Also should note that a number the items recently added were also previously removed because they now exist somewhere else in a more modern form (GridAssertions, GridView, FormBase, etc.).

**Comment by matthiaswh** [comment]
IMO these are better served in the [kegdemo](https://github.com/level12/keg-demo/) repo and users should be pointed there for reference.

If the worry is that the kegdemo repo will get out of date with cookiecutter or supporting libraries, we could likely setup CI to account for that.

But if we do end up keeping the demo code in the cookiecutter, can we move to using a flag to either include or remove it when instantiating a new app?

**Comment by guruofgentoo** [comment]
I would support having a flag for inclusion as long as it's opt-in.
