### ISSUE TITLE
drop xlrd requirement

### ISSUE THREAD

**Issue by guruofgentoo** [level12/keg-app-cookiecutter#140]
xlrd is a deprecated library useful only for reading older Excel files. Most (all?) of our libs support openpyxl at this point for reading Excel, so we should shift to using that as a default requirement if we keep one.

`assert_rendered_xls_matches` is the use case here. That now exists directly in `webgrid` along with the more modern `assert_rendered_xlsx_matches`.

**Comment by rsyring** [comment]
In progress as part of #141.  Closing.
