### ISSUE TITLE
remove GridAssertions and FormBase

### ISSUE THREAD

**Issue by guruofgentoo** [level12/keg-app-cookiecutter#141]
`GridAssertions` now has a counterpart directly in webgrid (`GridBase`).
`FormBase` is now in KegElements.

**Comment by rsyring** [comment]
@guruofgentoo I was going to remove GridAssertions, but it has a number of methods on it that webgrid testing utils don't seem to have.  In particular, the tests here the CC use `.assert_grid_matches(...)`.  Am I missing something or is a refactoring necessary?

**Comment by guruofgentoo** [comment]
We had a couple of sets of assertion methods going back a ways, so not all the methods made the cut when there were duplicate concepts. I'd expect `assert_grid_matches` to be pretty close to `expect_table_header` and `expect_table_contents`.
