### ISSUE TITLE
Update Celery worker cli args

### ISSUE THREAD

**Issue by rsyring** [level12/keg-app-cookiecutter#145]
See: https://github.com/level12/fis-src/pull/260/files

**Comment by guruofgentoo** [comment]
Did celery change the command sequence back to what it was before? We changed it earlier this year to reflect celery's newer ordering of args: https://github.com/level12/keg-app-cookiecutter/commit/58059ffad7d9a2afdabc2225faaa9a31268d055f#diff-51b892fbde2ac6b5359bb27ba874093529b4061bafc5ba4b0e81249abb23788f

**Comment by rsyring** [comment]
@guruofgentoo you are probably correct and I mislead us a bit.  Assuming the additional comments on the SRC PR are correct, then this issue is wrong and no fix is needed.
