### ISSUE TITLE
Add E123 to flake8 ignore list

### ISSUE THREAD

**Issue by rsyring** [level12/keg-app-cookiecutter#147]
Without it, this is flagged:

```python
   sql = sp_tbl.select() \
        .outerjoin(
            su_tbl,
            su_tbl.c.user_id == user_id,
        ).where(
            sp_tbl.c.type == type,
        )
```

And it seemingly wants this:

```python
    sql = sp_tbl.select() \
        .outerjoin(
            su_tbl,
            su_tbl.c.user_id == user_id,
    ).where(
            sp_tbl.c.type == type,
    )
```

**Comment by rsyring** [comment]
FWIW, I ended up adding columns to select, so it came out as:

```python
        sql = sp_tbl.select(
        // some columns
        ).outerjoin(
            su_tbl,
            su_tbl.c.user_id == user_id,
        ).where(
            sp_tbl.c.type == type,
        )
```

Which looked fine and made Flake8 happy.  For the case where no columns are needed, I'm guessing if I had done:

```python
        sql = sp_tbl.select(
        ).outerjoin(
            su_tbl,
            su_tbl.c.user_id == user_id,
        ).where(
            sp_tbl.c.type == type,
        )
```

Flake8 would have been fine with it?  I guess that's acceptable.  I withdraw my suggestion.

**Comment by matthiaswh** [comment]
@rsyring I usually would wrap that in another layer with enclosing parenthesis. It bugs me to put dependent chained function calls at the root level and I feel it does not mesh with Python's standard of indentation. In your example, `).outerjoin(` is given the same importance as `sql = `, without any sort of block annotation.

This way reads much more cleanly to me and I think is closer to what you originally wanted anyway.

```python
sql = (
    sp_tbl.select()
    .outerjoin(
        su_tbl,
        su_tbl.c.user_id == user_id,
    )
    .where(
        sp_tbl.c.type == type,
    )
)
```

I would also accept having the next function call on the same line as the closing parenthesis. `).where(` is fine, but keeping them separate makes it easier to comment out or remove an entire block without having to fiddle with the formatting.
