### ISSUE TITLE
Add a deploy playbook that keeps the current virtualenv

### ISSUE THREAD

**Issue by rsyring** [level12/keg-app-cookiecutter#152]
Discussion: https://github.com/level12/gb-spc/issues/621

Example at: https://github.com/level12/gb-spc/commit/eef32a76744965d8b05f103df55ee1ad9e351412

**Comment by guruofgentoo** [comment]
FWIW, we could just make the pyapp3 role smarter to compare hash of requirements file before/after checkout.
