### ISSUE TITLE
Add basic navigation

### ISSUE THREAD

**Issue by rsyring** [level12/keg-app-cookiecutter#45]
For reference: https://github.com/level12/pai-tangerine/commit/28e58a23cd0e6cfef1817ff3e1f77cc4fb6a342a#diff-1825cbab77686462fdec379dc145b2fb

**Comment by guruofgentoo** [comment]
I'll do this when I integrate KegAuth here - there are helpers that will limit the menu links based on the current user's permissions, or whether they're logged in.

**Comment by guruofgentoo** [comment]
Addressed in #62
