### ISSUE TITLE
Add default title block base-page.html

### ISSUE THREAD

**Issue by rsyring** [level12/keg-app-cookiecutter#47]
https://github.com/level12/pai-tangerine/commit/28e58a23cd0e6cfef1817ff3e1f77cc4fb6a342a#diff-7f70f0b7852e2b6ee8b91c3ec2c081c4R4

**Comment by guruofgentoo** [comment]
Looks like this got addressed elsewhere: https://github.com/level12/keg-app-cookiecutter/commit/d4ef32b785e56ad0033ba54b2bf33554709caaff#diff-73ba279653b7b2a42cec422d8d400cec
