### ISSUE TITLE
Add Flake8 ignore list including W503

### ISSUE THREAD

**Issue by rsyring** [level12/keg-app-cookiecutter#57]
Other projects have a Flake8 ignore list that varies considerably:

```ini
### RaceBetter
# E265 - block comment should start with '#'
# E123 - closing bracket does not match indentation of opening bracket's line
ignore = E265,E123

### Keg Auth
; W503 checks for line breaks before binary operators
ignore = E265,E123,E133,E226,E241,E242,W503

### FIS Climate
# E265 - block comment should start with # and two spaces
# E123, E133, E226, E241, E242: default Flake8
# E721 - "Do not compare types, use 'isinstance()'": False positives when comparing enum values
ignore = E265,E123,E133,E226,E241,E242,E731,W503,E721

## RRS Web Repo
ignore = E731,E305
```

What is our standard?  Also add W503 to the ignore list per https://level12.slack.com/archives/C02DAPS3T/p1542056998113700

Finally, I think I'd like to move Flake8 settings out of tox.ini and into setup.cfg.

**Comment by rsyring** [comment]
FYI, PR #62 has some discussion on this.

**Comment by rsyring** [comment]
@nZac and @guruofgentoo: I did some experimentation today and I think we should be more strict than the default ignore list.  This is what I'd like to use by default for our projects:

```ini
# E121 - A line is less indented than it should be for hanging indents.
# W503 - Line breaks should occur after the binary operator to keep all variable names aligned.
# Details & examples at: Errors: https://lintlyci.github.io/Flake8Rules/
[flake8]
max-line-length = 100
exclude=.git,.hg,.tox,dist,doc,*egg,build
ignore=E121,W503
```

If you have an existing project, you may swap W503 for W504 until you have time to clean things up.

**Comment by guruofgentoo** [comment]
Agree that being more strict is a good idea, and RRS is already (we don't even ignore E121 currently).

Two things (based on the current RRS list, which has been different from the above for around a year or so) for @rsyring opinion:
- what are your feelings on assigning simple lambda expressions vs breaking out those definitions into full defs? (that's E731)
- RRS currently ignores E252 (missing whitespace around parameter equals) because it gets triggered by type annotations in parameters with default values. We could just rip those out, but I was going to take some time this year to re-evaluate mypy and related tooling since it's been a couple years and may have become more useful.
  - I think the flake8 error here is a bug since it's been fixed in other projects (see https://github.com/PyCQA/pycodestyle/issues/753), but I haven't seen a ticket in flake8 for it. May need to start one...

**Comment by rsyring** [comment]
> we don't even ignore E121 currently

I don't either.  But I've honestly wanted more flexibility there at times.  I sometimes have really long first lines that might end up like this:

```python
some_long_thing, some_other_long_thing, maybe_a_third_thing = some_longish_function(foo, bar,
                                                                                    baz)
```

That usually forces me to do:

```python
some_long_thing, some_other_long_thing, maybe_a_third_thing = some_longish_function(
    foo,
    bar,
    baz,
)
```
to satisfy Flake8.  That's not necessarily a bad thing, but sometimes I feel like it's overkill.  Although, if we really want consistency, then I could drop E121 from the ignore list.

> what are your feelings on assigning simple lambda expressions vs breaking out those definitions into full defs? (that's E731)

I actually kind of like this approach, but have avoided it to pacify Flake8.  I'm a +1 on adding it to the ignore list.

> RRS currently ignores E252 (missing whitespace around parameter equals) because it gets triggered by type annotations in parameters with default values

I leave that up to you.  As a default, I'd say no.  If you need to add it custom for this reason, and we can't get better detection of this situation upstream, then I'd say it's ok to ignore if you are actually going to use the type annotations (either with mypy or simply find them valuable for declaring developer intent).

**Comment by rsyring** [comment]
Correction, I want to ignore E128, not E121: https://lintlyci.github.io/Flake8Rules/rules/E128.html

**Comment by rsyring** [comment]
> RRS currently ignores E252 (missing whitespace around parameter equals) because it gets triggered by type annotations in parameters with default values

[PEP 8 other recommendations](https://www.python.org/dev/peps/pep-0008/#other-recommendations) says this is the correct format:

```python
def __init__(self, _tote_states: Dict(ents.ToteSource, ToteState) = None):
```

And a current flake8 does not flag that for me.  Therefore, I don't think E252 is necessary?

**Comment by rsyring** [comment]
Turns out you need E121 and E128.  This is what I ended up with in RaceBetter:

```
# E121 - A line is less indented than it should be for hanging indents.
# E128 - Continuation line under-indented for visual indent.  To permit:
#   def some_log_function_call_with_params_on_next_line(race_day=race_day, system_id='A',
#       system_status='stopped', system_run_id='1')
# E731 - Lambdas should not be assigned to a variable. Instead, they should be defined as functions.
# W503 - Line breaks should occur after the binary operator to keep all variable names aligned.
# W504 - Line breaks should occur before the binary operator to keep all operators aligned.
# Details & examples at: Errors: https://lintlyci.github.io/Flake8Rules/
# According to discussion at: https://github.com/level12/keg-app-cookiecutter/issues/57
[flake8]
max-line-length = 100
exclude=.git,.hg,.tox,dist,doc,*egg,build
ignore=E121,E128,E731,W503,W504
```
For clarity on W503 v W504: "line breaks should occur before the binary operator because it keeps all operators aligned" therefore W503 should be in the ignore list, NOT W504.  But, in a legacy project, you may see both until you get everything converted.
