### ISSUE TITLE
Review Internal Initiatives

### ISSUE THREAD

**Issue by rsyring** [level12/keg-app-cookiecutter#72]
List items from "Internal Initiatives" of [Project Planning](https://level12.atlassian.net/wiki/spaces/DISCUSS/pages/95289365/Project+Planning) here.

Check them off if the work has been done or a separate issue has been created to track them.  If the latter, list issue number here.

* [x] Switch app authorized keys management to file-based method
* [x] Replace the wheelhouse with pip-tools #71
* [x] Move to using timestamped venvs during deploy

**Comment by guruofgentoo** [comment]
Also switched from git-crypt to LP.

Addressed in #62.
