### ISSUE TITLE
Add docker-compose file & create db if needed

### ISSUE THREAD

**Issue by rsyring** [level12/keg-app-cookiecutter#73]
https://level12.atlassian.net/wiki/spaces/devs/blog/2019/01/25/978092033/Docker+Usage

create db example: https://github.com/level12/racebetter/commit/77780a89dda67441c85ce81fb72ee0ab4659b070#diff-8d2fc170b9a3b3214cc9ed29eeb7ac68R70

**Comment by guruofgentoo** [comment]
Addressed in #62
