### ISSUE TITLE
Simplify local debugging for celery

### ISSUE THREAD

**Issue by nZac** [level12/keg-app-cookiecutter#93]
It's a bit frustrating right now when trying to run the Celery workers locally that you have to do two things to see info messages:

1) set the command line option `-l info` in _/scripts/celery-worker_
2) comment out `add_handler()` in `app.celery.worker`

Make it easier to see messages locally.

**Comment by rsyring** [comment]
`scripts/celery-worker` now has `KEG_LOG_STREAM_ENABLED=on` which results in info log messages going to stdout
