### ISSUE TITLE
Update sentry setup in celery worker

### ISSUE THREAD

**Issue by mtbrock** [level12/keg-app-cookiecutter#94]
Since we have moved to the new `sentry_sdk`, we need to update sentry registration in `celery/worker.py`. 

See https://github.com/level12/keg-app-cookiecutter/blob/f81958ca6ae67a19cc2db2e1392dd78da88bb5ab/%7B%7Bcookiecutter.project_dashed%7D%7D-src/%7B%7Bcookiecutter.project_namespace%7D%7D/celery/worker.py#L36

**Comment by guruofgentoo** [comment]
If I'm understanding correctly, https://github.com/level12/keg-app-cookiecutter/blob/f3fe42f1131805754bd4217099381383bffb774e/%7B%7Bcookiecutter.project_dashed%7D%7D-src/%7B%7Bcookiecutter.project_namespace%7D%7D/libs/sentry.py#L18 should be all the signal setup needed, and this block can just get removed.
